## EMBEDDED SERVER CONFIGURATION
server:
  port: 9090
## JPA
##mysql dialect
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.database: MYSQL
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://596606d883860.bj.cdb.myqcloud.com:9392/smart_park
#spring.datasource.username: root
#spring.datasource.password: lbjcbsq123
spring.datasource.url: jdbc:mysql://rm-bp1ppm0x8b509d802to.mysql.rds.aliyuncs.com:3306/smart_park
spring.datasource.username: wenwei
spring.datasource.password: wenwei@123
#createStudent createStudent-drop none validate update
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true
## JACKSON
spring.jackson.serialization.INDENT_OUTPUT: true
## ERRORS
error.whitelabel.enabled: true

spring.http.multipart.maxFileSize: 100Mb
spring.http.multipart.maxRequestSize: 100Mb

spring.resources.static-locations: classpath:/

## Logging configuration
logging:
  level:
    tk.mybatis: TRACE
    org.springframework:
      data: DEBUG
      security: DEBUG

druid:
  url: jdbc:mysql://596606d883860.bj.cdb.myqcloud.com:9392/smart_park
  username: root
  password: lbjcbsq123
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

mybatis:
  type-aliases-package: com.wenwei.guizi.domain.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
        - com.wenwei.guozi.utils.MyBatisMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
#  thymeleaf:
#    prefix: classpath:/api/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    cache: false

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
#  604800 -> 7 day
  tokenHead: "Bearer "
# Routes
route:
  authentication:
    auth: "/auth"
    refresh: "/refresh"
    register: "/auth/register"
  common:
    oss: "auth/oss"
    cosWeb: "/webauth"
    cosApp: "/appauth"
APP_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCY+Un5AnoTlcUWW0C7CUHShjstW+3oSeCIUuNCNPqkj26pl9qeZ4ImQ4EMSR+BPHZ79Xd0QblCjKLn9XXe9mP7svZPlJvSPDtTYp5X9zTLHwzcQJa8tC0/hfFlX+SQoCXADg2mMQvTUsKCBCOemd/llqjjiydxUaulkzcfY8xovJTT+PBzqD4eK+nVZuK/Kmv0BzRIjEBH4oKHOIsqyGTIoYJjN6VYfnP9CSaKaysfFemgZU0a3PEqxE8/p2xjhXdCM9hPKWqIe4l/IyEsK/o6XhzjHRi13/KrPaJCsvi2zFalq2glkNTGSQgwYkTEGlNoK2+xcMk0dPkaOJYj0zAtAgMBAAECggEAG2mQt+6ZsajFCJyRnPKruO4U7KvslhOnCMbRsquLvrF1Qy7THk+uIu010t3Hp4EOOmhiX5Lnf+Vzy91QogPFJvWK7ffTdHkWqHqjpV/HNh76Tv3EBUzETv3RpDjq3H/WQ/RAvedMFzJdaK8VMvagCKRW32+wQb5A5ArddeKMXrglM7N2s7MWpgX8kn7ssvyzHSslVLwjmrFv9HkF6JWjizDv6g7lEeSMyQva7kj0p/TEtbaci6m9WwCNHweE83BBostGfMR7m0GOqAnTnw5hB4PH21Xb5VPOezTRml4O6KE0FgylYhPIcwTX003Stx47wyEycP5NjEau+dRgm0UMAQKBgQDZvrZvXwPYfVfOJlcEn2KW2OhfpSHH2ibavLF8cLtrRvMOAc/cUoBMFD5nwhEF2fptPZYL2fXRt+DD5v1MAlbMrpgmi3Q+ZNz1zEMCDTBrnqW9vjwKw2JUNghWVWBv0Ep5UTDyVjEIwAULUCafZbUGLklaYs7wuTCexswlWVcGqQKBgQCz2W45E7sww8d+5kQziDU25XJ7WtbB3vmBTBNjGFER5xO0qfnwxDavooAFXNhWbVwU66GEKyRPeejyl7ED49vlc+/lNSs5ZfLDns95m8zRywxwmh3uqZp782RzWzGMPgwM9DNo7umulEaKpjahxfX64sGGnGR+RGrSSvrckdxD5QKBgGyO+qG3+1DZ3Qb4cnXpiNuwNNpKl/btumVfohVqluY7Lz6ShLFRqIlFpn9Qb/A85u/DvqUV+8qdJEBHT42vtNrDSTQeXswkuU0Kk3XYYYWmSPe6enDbTJCzh6CTXEsiy56EbiTD+BpmsZ0cTsU1jfUQ6p1XmdjGW4ktj+YnDo5RAoGAILHkUcf+faz5tV4TA/M9CU/I8hffdrscTJ8R3y/qfQCvGmbUIyrobiFyeIcaZQvYc40qfaaCIVieOovNCFICBcJ/2AFEbFjWOy3Bte/W2kS5bDb4PgzjIqlql3X6me4lrq0uM2NLZAtcj5QL1njwcL2MRPZlZnb1nGk5FaQGkOkCgYAIsM/oeoX9DgueZE6PTKySp81rrs1oeXTdDOhnJsg8UFyXF30pdWc8jkLu77L6ajxxW+EBP5uadqjoN87wBOEXlSknDjF47AaxdqacK1zYUtf2Io6/mvIVWvpmQtNhgf0h9mwN8oORs3dZi+hmigOQgic+ee9GbYRnFMazFH/mJQ==
ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmPlJ+QJ6E5XFFltAuwlB0oY7LVvt6EngiFLjQjT6pI9uqZfanmeCJkOBDEkfgTx2e/V3dEG5Qoyi5/V13vZj+7L2T5Sb0jw7U2KeV/c0yx8M3ECWvLQtP4XxZV/kkKAlwA4NpjEL01LCggQjnpnf5Zao44sncVGrpZM3H2PMaLyU0/jwc6g+Hivp1Wbivypr9Ac0SIxAR+KChziLKshkyKGCYzelWH5z/QkmimsrHxXpoGVNGtzxKsRPP6dsY4V3QjPYTylqiHuJfyMhLCv6Ol4c4x0Ytd/yqz2iQrL4tsxWpatoJZDUxkkIMGJExBpTaCtvsXDJNHT5GjiWI9MwLQIDAQAB
APP_ID: 2018013102118057